
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake4.1/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "D:/cmake4.1/share/cmake-4.1/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:4 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Users/mi/.dnx/bin/"
      - "C:/Program Files/Microsoft DNX/Dnvm/"
      - "C:/Program Files/Microsoft SQL Server/120/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/130/Tools/Binn/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR/"
      - "D:/tortoise/bin/"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "D:/cmake/bin/"
      - "C:/Program Files (x86)/MySQL/MySQL Fabric 1.5 & MySQL Utilities 1.5/"
      - "C:/Program Files (x86)/MySQL/MySQL Fabric 1.5 & MySQL Utilities 1.5/Doctrine extensions for PHP/"
      - "D:/nvim/bin/"
      - "D:/Git/cmd/"
      - "D:/pandoc/"
      - "C:/Program Files/usbipd-win/"
      - "D:/cmake4.1/bin/"
      - "D:/cursor/resources/app/bin/"
      - "C:/Users/mi/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/mi/.dotnet/tools/"
      - "D:/Typora/"
      - "D:/Microsoft VS Code/bin/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Users/mi/.dnx/bin/mingw32-make.exe.com"
      - "C:/Users/mi/.dnx/bin/mingw32-make.exe"
      - "C:/Program Files/Microsoft DNX/Dnvm/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft DNX/Dnvm/mingw32-make.exe"
      - "C:/Program Files/Microsoft SQL Server/120/Tools/Binn/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft SQL Server/120/Tools/Binn/mingw32-make.exe"
      - "C:/Program Files/Microsoft SQL Server/130/Tools/Binn/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft SQL Server/130/Tools/Binn/mingw32-make.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR/mingw32-make.exe.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR/mingw32-make.exe"
      - "D:/tortoise/bin/mingw32-make.exe.com"
      - "D:/tortoise/bin/mingw32-make.exe"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe"
      - "D:/cmake/bin/mingw32-make.exe.com"
      - "D:/cmake/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/MySQL/MySQL Fabric 1.5 & MySQL Utilities 1.5/mingw32-make.exe.com"
      - "C:/Program Files (x86)/MySQL/MySQL Fabric 1.5 & MySQL Utilities 1.5/mingw32-make.exe"
      - "C:/Program Files (x86)/MySQL/MySQL Fabric 1.5 & MySQL Utilities 1.5/Doctrine extensions for PHP/mingw32-make.exe.com"
      - "C:/Program Files (x86)/MySQL/MySQL Fabric 1.5 & MySQL Utilities 1.5/Doctrine extensions for PHP/mingw32-make.exe"
      - "D:/nvim/bin/mingw32-make.exe.com"
      - "D:/nvim/bin/mingw32-make.exe"
      - "D:/Git/cmd/mingw32-make.exe.com"
      - "D:/Git/cmd/mingw32-make.exe"
      - "D:/pandoc/mingw32-make.exe.com"
      - "D:/pandoc/mingw32-make.exe"
      - "C:/Program Files/usbipd-win/mingw32-make.exe.com"
      - "C:/Program Files/usbipd-win/mingw32-make.exe"
      - "D:/cmake4.1/bin/mingw32-make.exe.com"
      - "D:/cmake4.1/bin/mingw32-make.exe"
      - "D:/cursor/resources/app/bin/mingw32-make.exe.com"
      - "D:/cursor/resources/app/bin/mingw32-make.exe"
      - "C:/Users/mi/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/mi/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/mi/.dotnet/tools/mingw32-make.exe.com"
      - "C:/Users/mi/.dotnet/tools/mingw32-make.exe"
      - "D:/Typora/mingw32-make.exe.com"
      - "D:/Typora/mingw32-make.exe"
      - "D:/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "D:/Microsoft VS Code/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Users\\mi\\.dnx\\bin"
        - "C:\\Program Files\\Microsoft DNX\\Dnvm\\"
        - "C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\"
        - "C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR"
        - "D:\\tortoise\\bin"
        - "C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "D:\\cmake\\bin\\"
        - "C:\\Program Files (x86)\\MySQL\\MySQL Fabric 1.5 & MySQL Utilities 1.5\\"
        - "C:\\Program Files (x86)\\MySQL\\MySQL Fabric 1.5 & MySQL Utilities 1.5\\Doctrine extensions for PHP\\"
        - "D:\\nvim\\bin"
        - "D:\\Git\\cmd"
        - "D:\\pandoc\\"
        - "C:\\Program Files\\usbipd-win\\"
        - "D:\\cmake4.1\\bin\\"
        - "D:\\cursor\\resources\\app\\bin"
        - "C:\\Users\\mi\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\mi\\.dotnet\\tools"
        - "D:\\Typora\\"
        - "D:\\Microsoft VS Code\\bin"
...
